### PR TITLE
Replace the old webfontloader with  ffontsloader

### PR DESCRIPTION
**Pull request by p4535992**
Hi the version of webfontloader was very old and doesn't seem to be followed anymore.
I found an opensource project with the same license and newer that seems to work well,  https://github.com/MurDaD/ffontsloader

Try to have a look at it just in case or put the latest version of webfontloader in the project (we were on the third last one)

### CODE REVIEW

**Comment by megahead11** [comment]
I'll try and give this a test before I merge this; might need a day or so

**Comment by megahead11** [comment]
On initial testing, for whatever reasons, it doesn't seem to initialize the UI for theatre (on the right side), 
I receive this error on my empty world (with this and anonymous enabled). The issue still happens even with theatre on its own.
image

**Comment by p4535992** [comment]
Exported the constants on the theatre class should be fixed this issue... next pr i will create constants file for a cleaner code

**Comment by p4535992** [comment]
k should be working now, try out and let me know it

**Comment by megahead11** [comment]
Looks good! I'll go ahead and merge this.

**Comment by p4535992** [comment]
@megahead11 i made  a mistake on this pr can you add this line to the setup hook ?

Hooks.once("setup", () => {
  theatre = new Theatre();

  **window.Theatre = theatre;**

**Pull request merged**
