### PR TITLE
Hide By CSS Selectors

### PR DESCRIPTION
**Pull request by Oxy949**
Adds the ability to hide elements specified by CSS selectors when the stage is active:
image

### CODE REVIEW

**Comment by megahead11** [comment]
This is a pretty unusual setting to be adding, in my opinion. 
Out of curiosity, what common elements/use cases would people want to hide? Is this for specific systems?

**Comment by Oxy949** [comment]
> This is a pretty unusual setting to be adding, in my opinion (but not unwelcome). Out of curiosity, what common elements/use cases would people want to hide? Is this for specific systems?

Hi! I use [Small Time](https://github.com/unsoluble/smalltime) module for time indication. But it's default position is above players list: 
Screenshot (2)

So using the settings I hide `#smalltime-app` when the stage is active:
Screenshot (4)

**Comment by megahead11** [comment]
Oh, my bad. I didn't see the small time selector in the image; I actually assumed it was for the app itself!
That makes a lot more sense, although I feel like Custom CSS (another module) achieves a similar result. I will still accept this PR though , since it would be nice for people who don't want to use it :)

**Comment by Oxy949** [comment]
> Oh, my bad. I didn't see the small time selector in the image; I actually assumed it was for the app itself!
> That makes a lot more sense, although I feel like Custom CSS (another module) achieves a similar result. I will still accept this PR though , since it would be nice for people who don't want to use it :)

Actually no, Custom CSS won't allows you to do this. It allows you to instantly hide things (the time widget for example) but not to do this exactly when the stage is active. The only option to hide elements (without the setting in the PR) is by using Custom CSS AND a custom hook for `theatreDockActive` to change classes of target elements.

**Pull request merged**
